-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Mahsa\Desktop\Th1008_Code\tanh_vhld_piecewise_linear\codegen\vhdl_approximate_tanh_design\hdlsrc\vhdl_approximate_tanh_design_fixpt_pkg.vhd
-- Created: 2021-08-21 19:45:46
-- 
-- Generated by MATLAB 9.8, MATLAB Coder 5.0 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE vhdl_approximate_tanh_design_fixpt_pkg IS
  TYPE vector_of_std_logic_vector14 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(13 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_real IS ARRAY (NATURAL RANGE <>) OF real;
  TYPE vector_of_signed29 IS ARRAY (NATURAL RANGE <>) OF signed(28 DOWNTO 0);
  TYPE vector_of_signed28 IS ARRAY (NATURAL RANGE <>) OF signed(27 DOWNTO 0);
  TYPE vector_of_unsigned32 IS ARRAY (NATURAL RANGE <>) OF unsigned(31 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
END vhdl_approximate_tanh_design_fixpt_pkg;

